### ISSUE TITLE
小程序上线域名

### ISSUE THREAD

**Issue by Zz-ZzzZ** [TheKonka/v2ex-mini#1]
作者你好，我在使用`v2ex`的`ap`i进行`taro`相关的学习使用，想请问一下你的小程序上线时服务器域名是怎么填的，直接输入`https://www.v2ex.com`会被告知未备案。

**Comment by TheKonka** [comment]
你好，小程序域名必须是 备案了的域名，并且 v2ex 官网国内访问也有网络问题，上线使用官方域名肯定不行。
我是请求自己已备案的域名的 三级域名，同时三级域名 记录指向境外vps ，通过 nginx 反代 到 v2ex 官网

**Comment by Zz-ZzzZ** [comment]
了解了，感谢回复~
